### PR TITLE
Ashlar version update

### PR DESCRIPTION
**Pull request by CameronFRWatson**
ASHLAR version update to 1.18.0. See tool repo: https://github.com/labsyspharm/ashlar/releases/tag/v1.18.0

### CODE REVIEW

**Comment by CameronFRWatson** [comment]
@bgruening We updated this tool from 1.14 to 1.18. Given that the tool version is changing, should we also increment the VERSION_SUFFIX for the wrapper (from 1 to 2)? Or because it's a new version of the tool itself, the wrapper version suffix would reset to 1? Thank you!

**Comment by bgruening** [comment]
You can reset the SUFFIX back to 0 if you have a new major version. Can you also please look at the linter warnings?

**Comment by CameronFRWatson** [comment]
Thanks @bgruening for the quick response! I addressed the lint warnings, and will do the same for the other tools as we go through and make updates

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @CameronFRWatson

**Pull request merged**
