### PR TITLE
Add tests for Palom

### PR DESCRIPTION
**Pull request by alliecreason**

### CODE REVIEW

**Comment by bgruening** [comment]
The test data is 60MB. Is there anything smallee that we can use?

**Comment by alliecreason** [comment]
Some of these tools tend to fail on smaller images. @CameronFRWatson is that the case for palom?

**Comment by CameronFRWatson** [comment]
@bgruening @alliecreason It's difficult to find `.svs` images under 30MB that still have features for the tool to align, and they can't be cropped due to the proprietary nature of the format so I can't make these ones smaller.

**Comment by bgruening** [comment]
A bit of background.

* Large test data makes handling github repos harder, especially for new contributors with slow internet.
* Test data will be uploaded to the TS, where is also waste space - with 8000 tools this is a considerable amount.
* test-data will also be downloaded into you Galaxy server where you install your tool - and this with every version again - so every version of palom will have 60MB of data on your Galaxy server --> they are actually used for some minor use-cases

We know this is not ideal and we have discussed for years now that it would be ideal to define in the Galaxy XML a URI to the data. So that planemo downloads the data from a URI and does not assume it is stored in git. However, we have not done this yet and working around these issues with various hacks. See also https://github.com/galaxyproject/planemo/issues/1268 for a recent conversation.

Another aspect that I wanted to point you to is that you can define tests that are failing. Failing in a specific way is good, we know the tool is working in theory and fails with a defined way and this you can define in the XML (https://docs.galaxyproject.org/en/latest/dev/schema.html#id92).

I don't know what the best way is before we have the URI feature. Feel free to merge, it looks good to me besides the large test data.

**Pull request merged**
